import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import ActiveSectionContextProvider from "@/context/active-section-context";
// import ThemeSwitch from "@/components/theme-switch";
// import ThemeContexrProvider from "@/context/theme-context";
// import { Toaster } from "react-hot-toast";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Abigai's Portfolio",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-950 relative`}>
//         <div className="bg-[#f8704688] absolute top-[-10vh] -z-10 right-[-5vw] h-[30vh] w-[30vh] rounded-full blur-[10rem] sm:w-[60vw] sm:h-[60vw]"></div>
//         <div className="bg-[#9bbcff88] absolute top-[-5vh] -z-10 left-[-30vw] h-[30vh] w-[50vw] rounded-full blur-[10rem] sm:w-[60vw] sm:h-[60vw] md:left-[-25vw] lg:left-[-20vw] xl:left-[-15vw]"></div>
        
//         <Header />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-950 relative`}>
        {/* <ThemeContextProvider>
          <ActiveSectionContextProvider> */}
        <div className="bg-[#f870467d] absolute top-[-6rem] -z-10 right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem] "></div>
        <div className="bg-[#9bbcff82] absolute top-[-1rem] -z-10 left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]"></div>

          
          <Header />
          {children}
          <Footer />

          {/* <Toaster position="top-right" />
          <ThemeSwitch/>
          </ActiveSectionContextProvider>
        </ThemeContextProvider> */}
       
      </body>
    </html>
  );
}